name       : girara
version    : 0.3.5
release    : 10
source     :
    - https://github.com/pwmt/girara/archive/0.3.5.tar.gz : ce6bc8cb95ec886dc01c6ce8ea8ccf1d17db523d78dec1aa380115b2804971d8
homepage   : https://pwmt.org/projects/girara/
license    : Zlib
component  : programming.library
summary    : A user interface library that focuses on simplicity and minimalism
description: |
    girara is a library that implements a user interface that focuses on simplicity and minimalism.
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(json-c)
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
