name       : girara
version    : 0.2.7
release    : 2
source     :
    - https://pwmt.org/projects/girara/download/girara-0.2.7.tar.gz : 98e6a343298ae46869c990bc6e0732555e19af2e386cdc1a911f109b1c5c32e5
license    : BSD-3-Clause
component  : programming
summary    : girara is a library that implements a user interface that focuses on simplicity and minimalism.
description: |
    girara is a library that implements a user interface that focuses on simplicity and minimalism.
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libnotify)
    - intltool
build      : |
    %make
install    : |
    %make_install
    rm $installdir/usr/lib/libgirara-gtk3.a
