name       : girara
version    : 0.3.0
release    : 3
source     :
    - https://pwmt.org/projects/girara/download/girara-0.3.0.tar.xz : b752fa5ff0a98cfa773bbcf66bb8a5e337a61cbb085d6577b3979178d17e41a2
license    : BSD-3-Clause
component  : programming
summary    : girara is a library that implements a user interface that focuses on simplicity and minimalism.
description: |
    girara is a library that implements a user interface that focuses on simplicity and minimalism.
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(json-c)
    - pkgconfig(libnotify)
    - intltool
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
