name       : girara
version    : 0.3.1
release    : 4
source     :
    - https://pwmt.org/projects/girara/download/girara-0.3.1.tar.xz : 3c409bac00b6628aa80c601a64e11c3ff07a3c0721ac80436eceb282cb55bcb5
license    : BSD-3-Clause
component  : programming
summary    : girara is a library that implements a user interface that focuses on simplicity and minimalism.
description: |
    girara is a library that implements a user interface that focuses on simplicity and minimalism.
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(json-c)
    - intltool
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
