name       : girara
version    : 0.2.6
release    : 1
source     :
    - https://pwmt.org/projects/girara/download/girara-0.2.6.tar.gz : eba69b3522b4d149e06d133de52877913275873c505993fad08b6d7884ec9a0f
license    : BSD-3-Clause
component  : programming
summary    : girara is a library that implements a user interface that focuses on simplicity and minimalism.
description: |
    girara is a library that implements a user interface that focuses on simplicity and minimalism.
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libnotify)
    - intltool
build      : |
    %make
install    : |
    %make_install
    rm $installdir/usr/lib/libgirara-gtk3.a