name       : girara
version    : 0.3.4
release    : 8
source     :
    - https://github.com/pwmt/girara/archive/0.3.4.tar.gz : 84d4f81ee38af7f9024113eb31a5d818f7f00035a914aa99728944fe49d6ed23
homepage   : https://pwmt.org/projects/girara/
license    : Zlib
component  : programming
summary    : girara is a library that implements a user interface that focuses on simplicity and minimalism.
description: |
    girara is a library that implements a user interface that focuses on simplicity and minimalism.
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(json-c)
    - intltool
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
