name       : girara
version    : 0.3.2
release    : 6
source     :
    - https://github.com/pwmt/girara/archive/0.3.2.tar.gz : bda025069e9fb056b6d8e5b2d8b029082abeda080b82bd937dd0dccf5ef36e57
license    : BSD-3-Clause
component  : programming
summary    : girara is a library that implements a user interface that focuses on simplicity and minimalism.
description: |
    girara is a library that implements a user interface that focuses on simplicity and minimalism.
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(json-c)
    - intltool
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
