name       : girara
version    : 0.3.3
release    : 7
source     :
    - https://github.com/pwmt/girara/archive/0.3.3.tar.gz : 4456ddd6f0420fa6f1677a4a8f438f0401c38c2521585db3ee42e339a730798f
license    : Zlib
component  : programming
summary    : girara is a library that implements a user interface that focuses on simplicity and minimalism.
description: |
    girara is a library that implements a user interface that focuses on simplicity and minimalism.
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(json-c)
    - intltool
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
