name       : girara
version    : 0.3.8
release    : 12
source     :
    - https://git.pwmt.org/pwmt/girara/-/archive/0.3.8/girara-0.3.8.tar.gz : 627c1960bd848d37a889e462391dae0f9b525718d4600058c87a28252f46f2ca
homepage   : https://git.pwmt.org/pwmt/girara
license    : Zlib
component  : programming.library
summary    : A user interface library that focuses on simplicity and minimalism
description: |
    girara is a library that implements a user interface that focuses on simplicity and minimalism.
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(json-glib-1.0)
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
