name       : girara
version    : 0.4.0
release    : 13
source     :
    - https://git.pwmt.org/pwmt/girara/-/archive/0.4.0/girara-0.4.0.tar.gz : 24edfa3d493e7d4bbf491bb730d036cfedbd6c34ada1a7cfcd6273e78cffa44c
homepage   : https://git.pwmt.org/pwmt/girara
license    : Zlib
component  : programming.library
summary    : A user interface library that focuses on simplicity and minimalism
description: |
    girara is a library that implements a user interface that focuses on simplicity and minimalism.
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(json-glib-1.0)
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
