name       : girara
version    : 0.3.7
release    : 11
source     :
    - https://git.pwmt.org/pwmt/girara/-/archive/0.3.7/girara-0.3.7.tar.gz : 41342213f8e745258f1db28cbb6ccc27a63009a5e001bf791bbe01ce436d4db7
homepage   : https://git.pwmt.org/pwmt/girara
license    : Zlib
component  : programming.library
summary    : A user interface library that focuses on simplicity and minimalism
description: |
    girara is a library that implements a user interface that focuses on simplicity and minimalism.
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(json-c)
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
